hash-format = "sha256"

[[files]]
file = "config/armorposer.toml"
hash = "3d722c9b0301d7b8766ac9ee1aa5ca52ad3a46012185a1db2fe348aece6534d3"

[[files]]
file = "config/axiom/.axiom.json.backup"
hash = "0da032838f484f1cd4988f6ff43b283b7c50942be892488f29d917cc4fa7363d"

[[files]]
file = "config/axiom/axiom.json"
hash = "0da032838f484f1cd4988f6ff43b283b7c50942be892488f29d917cc4fa7363d"

[[files]]
file = "config/axiom/imgui.ini"
hash = "7cdd0c29bb896347a5a4470829df541361ccb0e4963a6cc4f930b1141050a808"

[[files]]
file = "config/bundles_beyond.json"
hash = "b843d2b61d146d19d70c7e814fc81d3b0edc334254631551b362dfb37db0ccf4"

[[files]]
file = "config/camerautils/camerautils.properties"
hash = "8bdcf7cfc1560b125422842d71c40fa61c5bfa3da7b5f07517bc9825890f621a"

[[files]]
file = "config/chat_heads.json5"
hash = "2e33e5590888ad9c37d35ef6ef29d50e8ab7430ee7fd572a69b3583428abebf9"

[[files]]
file = "config/fabric/indigo-renderer.properties"
hash = "7457c798601e4b190ff4478afa62bd8026c9bee9a5952f9f669a0681c5b79302"

[[files]]
file = "config/freecam.json5"
hash = "442d3c73c8d0c64a2445ef0c31b618db0034a2f452bf15751ec337287f34ef0c"

[[files]]
file = "config/itemswapper-server-cache.json"
hash = "4dbbc3a53c61363de3a175980faa30d684da945c8175945f788236f9f9f03c4d"

[[files]]
file = "config/itemswapper.json"
hash = "1e90db9bb7936724d1de6dc911e51e33dfd8718db15a194ecc2565eaf21eb413"

[[files]]
file = "config/libjf-config-core-v2.json5"
hash = "c1894c52b296fb7ee7aad6701ccddd5419d21405a3e6d40a5e5b2f8afe2e85b4"

[[files]]
file = "config/libjf-translate-v1.json5"
hash = "d0fec97b89fee5e93df256afb8776ad332506303c811cf1b0022a033e9d691f2"

[[files]]
file = "config/libjf-web-v1.json5"
hash = "8d27c069a7eda5645111dffb2d61d480b18ea8c51a286fc8468d5b23a26403b9"

[[files]]
file = "config/litematica.json"
hash = "70e2550788ca793240c50a196c35e8800762cc5e1ee3e486c502008416b05632"

[[files]]
file = "config/litematica/litematica_haven.gregorsharpe.com.json"
hash = "12174fd2e7b7105aa4aa98a486df7baa470fd770ff30a731cf314c4fd571701a"

[[files]]
file = "config/litematica/litematica_haven.gregorsharpe.com_dim_minecraft_overworld.json"
hash = "adcadb841e38244e0121845e5c11366cb7fca48d1e6518db75eb8369eb9cc582"

[[files]]
file = "config/lithium.properties"
hash = "4f5890cb55b35047fdb433efa30060827aa9415e0850220f85b2c8ad663d6722"

[[files]]
file = "config/locator-heads.json"
hash = "981e6a4c39444fd0b54bc5bc7be243bb10d6082aa676762165b0eb0000b64e1b"

[[files]]
file = "config/malilib.json"
hash = "33d9f347c14aeaa05b845cb56a9704e979f0aa54c29165827f2980a688f344f6"

[[files]]
file = "config/minihud.json"
hash = "eb9827c28e4bd2a873850fcf886b278b54aff3aa89804646521e69d92a0d8614"

[[files]]
file = "config/minihud/haven.gregorsharpe.com.json"
hash = "92dde437e88be9b9efa176f7e600207b8f00953ddca11ff7f77409584bcc0ced"

[[files]]
file = "config/minihud/haven.gregorsharpe.com_dim_minecraft_overworld.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/modmenu.json"
hash = "16d20c40cc6c114faff5493b561873fe160a65047720bc19fb3a3dd64aa67f3b"

[[files]]
file = "config/peek/peek.properties"
hash = "4d9862054cd7c1cad30efb2d993d232061e1f5369df5d1d5bdc0d689361576f1"

[[files]]
file = "config/raised.json"
hash = "1155857d13e07bf99d7f6b70000a4035da3e6655aac2d6ffc51dba33730f5c1d"

[[files]]
file = "config/resourcepackchecker/resourcepackchecker.properties"
hash = "f5370c44c6d550547e803d980ffd2ed9f1edc6c8f1933e1eebd16d56934532c3"

[[files]]
file = "config/respackopts/_respackopts.conf"
hash = "8e42c76481421e2b3f3c83481e3920319b78b69c6c987e02e4c52bc7ea4e1be4"

[[files]]
file = "config/scribble.json"
hash = "70bba512c19c9883541dc9eebbb2d66c2a31db025a2bc183b731581582aa60a5"

[[files]]
file = "config/shulkerboxtooltip.json5"
hash = "b161733244a2e5f87e81fb11dac35d85f887a1011d4c5855e33fc4965da2b8e1"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "cf87542a5e97d96bcb42ed0c263d86fd25b8aa0bbec7351007507fae5ff5576f"

[[files]]
file = "config/sodium-mixins.properties"
hash = "b627c4456e6fa0bc4b5f85e2f1cd949faedae3cb9afdaf2a5f52e6f3b6ae1f01"

[[files]]
file = "config/sodium-options.json"
hash = "d3482af3895ad31a3b9c59b26807eb9944ede706b3d314668ad83c94d61bd195"

[[files]]
file = "config/sss-config.json"
hash = "e57456c82cd121070295d04cd040af8b453f4dc1cf481d69cfc2fbc521ded0fe"

[[files]]
file = "config/status/state-client.properties"
hash = "af8ac5d70bf81460fabfb5ac60919569006bd2ce14e6cd5cfccab04b5cb7bbee"

[[files]]
file = "config/voicechat/category-volumes.properties"
hash = "94c1c4f70e5b995fbd71e86d4fa646030437fecae0685875b560a55fbd0d0e56"

[[files]]
file = "config/voicechat/player-volumes.properties"
hash = "0332261861a5ace96f503e85b0d48a8df74ea6c2f3545cd229543a6afb55ad96"

[[files]]
file = "config/voicechat/translations.properties"
hash = "693643b1d393cbb3ea7f062afc4474fcd66e4036c4f8d7c056434979cbf512d1"

[[files]]
file = "config/voicechat/username-cache.json"
hash = "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"

[[files]]
file = "config/voicechat/voicechat-client.properties"
hash = "99a7e562d80a1c1535b024dc32ba58bd1d6702d64a4a82ae871f52821e83d182"

[[files]]
file = "config/voicechat/voicechat-server.properties"
hash = "4d0be0e743b48609d932f435f0dd496041c6eb0356691ef5c22b786d137987a3"

[[files]]
file = "mods/armor-poser.pw.toml"
hash = "b659fbc80c2d4377d2c50eba4119ba033906fb10bb3df3142fcd31e525983c6b"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "518d6273b6272750e2edef1a372fd6c2be60670f5ff00887aef6e19f470bfe41"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "e80c6652b75192f5823cd725d1ef079e1d30b9df2fd655134a31b781c9c86068"
metafile = true

[[files]]
file = "mods/bundles-beyond.pw.toml"
hash = "974869c564ba74f0ae34d82d242b868c532d97ff83383c81d4d09551ed87fe5f"
metafile = true

[[files]]
file = "mods/camera-utils.pw.toml"
hash = "fbfff447728e018319cc1413d91d2c33ca32556e095c97eba493d6c09d1f021a"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "ce90f8ef06f71c6de7d2fe2623390f2e58e0be5284581ba4933a42a4e3aa9977"
metafile = true

[[files]]
file = "mods/chat-signing-hider.pw.toml"
hash = "8d8863656d46706d357eec0aaf440b0262863d0172463091c5927a570f5e9451"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "dbc4d5a60092831b89c3d1b697b43324b268cb970bf01786a0edb1a7e001d87d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b2103de7f3d13a7b7868890afd358e51f93bea4914e226fc0fbe53bdb84ff7e8"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "5a10992f3a471021e3a1c63727b7437dc04190efd5f3be1531bfb9f0b08230e9"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "fa8be992c1e3efbd030ef6a84409b766a936deb3fc3d06b657f8e468745044f0"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "db4ea89ef39c92aa7b85a22ab5f84959784ab9dcdf2c9507f2960703c7ab9c28"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e40c635ba1ed5d31678382038ae61d5aebdf6e0ae247e00126de812c2038c0af"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "67fcdafe078bc644bbb14575d6e2623aef931adf52e48f4f3cfea8c1c8fce305"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "ec8cf571adb8f71dbac6dae6f9d804fa810999b8c9fcfa3c20b07addc0a07936"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "bc5613671afa5f828b667b70385e1323227dbd91ce66cf5ae7128198c59849da"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5787b1deb7975af608901df0bf16b1e5de2452c98808f6a205c35aaa83e9f56a"
metafile = true

[[files]]
file = "mods/locator-heads.pw.toml"
hash = "55b3ec84f9acee87ee718e4c315cdf5e86c0e882c55a98a53034ff3bf5307218"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "ff6121108daaf566d8899fbd2b9359a98ca627b99399dc9a34c1019fbfd2eaac"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "e1fb3d150181a968b1d428def3cca9e4b328b9dc2f1bb006e469732aabf80ee6"
metafile = true

[[files]]
file = "mods/model-browser.pw.toml"
hash = "fe290be05d016aa1d7813b79005575c2ed2f56dc4a9202d8842270af12820fe2"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "9cb7b03b45eb9eede9748fd6dfb4de9396378ce7883da6d0da657675c7aa060d"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "5a8266ecf742e57419d77b2ab0a55697243a7f6ea68bf61f3ec1b0e059dec7ed"
metafile = true

[[files]]
file = "mods/peek.pw.toml"
hash = "3f147bbd3c21b5684c5e7a6dfc33acb2c86ee082ff197f9fc0aa835fd2c35f82"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "3aac9c45822ac00fdb0f2b834e0020af0c78a559681540e25af8c67bbca3cc8d"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
hash = "1390f7d5403e433f9f84d14e39b14f718e597a4e70b78129b0e93c9d394c9b72"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "06f3344c455836ebb0f08fd5b35d5d2894b102080d1f81e92c1a50a5a0ea9bde"
metafile = true

[[files]]
file = "mods/scribble.pw.toml"
hash = "6f6ca7ad199c17f66e007443bc7d8179889afb2084b0e1afa0f03afc24387ffb"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "590bd71a45f826c5e1ecda3adf133b19731ab9dc74d6582d259562aed70f2db2"
metafile = true

[[files]]
file = "mods/server-resource-pack-checker.pw.toml"
hash = "47e3ae2a0f6862e8523662191f06e57719151b68dbcfbf44c3016c02f3ea8dc0"
metafile = true

[[files]]
file = "mods/shadeandsaturation.pw.toml"
hash = "05c40bc41b08cc311dfd2a9f97da077bbd1711180634bd34697cdfda72fee597"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "7480a3c2deca7eaa725db9981af97833151a7cbf3027c823f577e43032396b38"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "233e1f6a3c1f2aaae3f311168e62bbae8c894923e65866b27c689ac0bcd60dde"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "fbb68e5991ad23a75679bc7deae303166393ec3108e40d133054a4cc8914e5fd"
metafile = true

[[files]]
file = "mods/status.pw.toml"
hash = "a3fdb97f15b9afc78c87ff7d98818f4451057fd4a8b16acf3fc513627abcc538"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "39b4cccb2535a746e6597c84eaaa3052c0c20f2dd0704dfe853ffa5853dfb3d6"
metafile = true

[[files]]
file = "resourcepacks/hoffens-minimal-armor.pw.toml"
hash = "a7e5f2a2661a4ef25fe71914edc2b1c29d4acd11479c163c31d09f9be26dc42d"
metafile = true

[[files]]
file = "servers.dat"
hash = "40c78fef5c900945856f41229d8659c4b9e80d605ba74ed53c28fd123f55677a"

[[files]]
file = "shaderpacks/SEUS PTGI E12.zip"
hash = "929754228be39a7a3407be6f3c7f8f8f6fe84c14319840f9c3bba5695796ee4f"

[[files]]
file = "shaderpacks/SEUS-Renewed-v1.0.1.zip"
hash = "76a1ff6c0d7827ecd0857e5a9b5298337f232662767abf0f011154c85b6da8ef"

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "5f9f72aacbc0041056412f18dd6ea18aa87a39307e7cd2babd80910e242fcb71"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "a6069e50f5f040ca578879297c8be5bb4affc4abeb83438bce51c801f938a564"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "c363c5cebefc114a08ca1bd415521554dc5d1ee7ef3843adad4846be548816ec"
metafile = true

[[files]]
file = "shaderpacks/makeup-ultra-fast-shaders.pw.toml"
hash = "fef87582943760a2b187cc494f4b1f55b40425874a003fb221d1f4692331372c"
metafile = true

[[files]]
file = "shaderpacks/sildurs-vibrant-shaders.pw.toml"
hash = "626b928a06444e7b76bf804e1b880cea3baf2bf2c42bcca6e25517592f103ee8"
metafile = true

[[files]]
file = "shaderpacks/solas-shader.pw.toml"
hash = "90f0f949d1c5caec84b32ad9e4c773b1df4a00e250dabc9e6d3782bc22c385ba"
metafile = true
