name = "Hermits Hearth"
author = "Waveformal (Base pack by Xisumavoid)"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b94b3201e5b2645d364d1eb25437c40827fcb22e7f999f1025ad1e2898dfc4f"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
